service: serverlessoffline

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  region: eu-west-1
  lambdaHashingVersion: 20201221
  stage: dev

plugins:
  - serverless-offline
  
functions:
  hello:
    handler: handler.hello
    description: "slspress offline example"
    events:
      - http:
          path: /example
          method: get
          cors: true

  getHome:
    handler: functions/home.home
    description: "slspress offline Home"
    events:
      - http:
          path: /
          method: get
          cors: true

  getVersion:
    handler: functions/version.version
    description: "version of the server"
    events:
      - http:
          path: /version
          method: get
          cors: true

  getUser:
    handler: functions/user/get.getUser
    description: "User get Route"
    events:
      - http:
          path: /user
          method: get
          cors: true

  createUser:
    handler: functions/user/create.createUser
    description: "User get Route"
    events:
      - http:
          path: /user
          method: post
          cors: true